[project]
name = "flares"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "danteherrera1999", email = "dante.herrera.1999@gmail.com" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
flares = "flares:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
